name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Build Docker images
      - name: Build Docker Images
        run: docker-compose build

      # Run tests
      - name: Run Backend Tests
        run: docker-compose run --rm backend npm test

      - name: Run Frontend Tests
        run: docker-compose run --rm frontend npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Deploy the application
      - name: Deploy Application
        run: |
          docker-compose down
          docker-compose up -d
