name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies with pnpm
        run: |
          npm install -g pnpm
          pnpm install

      # Lint the code
      - name: Run linter
        run: pnpm lint

      # Run unit tests
      - name: Run unit tests
        run: pnpm test

      # Build the app
      - name: Build the app
        run: pnpm run build

      # Test the Dockerfile
  docker-build-test:
    name: Test Dockerfile Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and test Docker image
      - name: Build Docker image
        run: |
          docker build -t frontend-test-app -f Frontend/Dockerfile .
          docker run --rm -d -p 3000:3000 frontend-test-app

      # Ensure the app is running and accessible
      - name: Check application health
        run: curl --fail http://localhost:3000 || exit 1
