name: Frontend Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'  # This will cache pnpm dependencies

    # Step 3: Install pnpm globally (if not already present)
    - name: Install pnpm
      run: npm install -g pnpm

    # Step 4: Install dependencies using pnpm
    - name: Install dependencies
      run: pnpm install

    # Step 5: Build the frontend Docker image
    - name: Build Docker Image
      run: docker build -t frontend-test-app -f Frontend/Dockerfile .

    # Step 6: Run tests (if you have tests configured)
    - name: Run tests
      run: pnpm run test  # Adjust this if you have specific test commands
