name: Frontend Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Verify pnpm installation
      - name: Verify pnpm installation
        run: pnpm --version

      # List files in the Frontend directory to verify that package.json exists
      - name: List files in Frontend directory
        run: ls -R Frontend

      # Install dependencies inside the Frontend directory
      - name: Install dependencies
        run: pnpm install
        working-directory: Frontend

      # Run tests (if any) inside Frontend directory
      - name: Run tests
        run: pnpm test
        working-directory: Frontend

      # Build the application inside Frontend directory
      - name: Build application
        run: pnpm run build
        working-directory: Frontend

      # Verify Docker build inside Frontend directory
      - name: Docker build
        run: docker build -t frontend-test-app -f Frontend/Dockerfile .
