name: Frontend Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install
        working-directory: Frontend

      # Run tests (if you have any)
      - name: Run tests
        run: pnpm test
        working-directory: Frontend

      # Build the application
      - name: Build application
        run: pnpm run build
        working-directory: Frontend

      # Verify Docker build
      - name: Docker build
        run: docker build -t frontend-test-app -f Frontend/Dockerfile .
