name: Build SvelteKit Application

on:
  push:
    branches:
      - main  # Set this to the branch from which you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Ensure you are using the latest version as of your current date

    - name: Setup Node.js
      uses: actions/setup-node@v5  # Latest version, ensuring compatibility with Node 20
      with:
        node-version: '20'  # Node.js 20, aligning with GitHub's environment updates

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Run Tests
      run: npm run test
