name: Build SvelteKit Application

on:
  push:
    branches:
      - main  # Set this to the branch from which you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Updated to the latest major version

    - name: Setup Node.js
      uses: actions/setup-node@v4  # Updated to the latest major version
      with:
        node-version: '20'  # Updated to the latest LTS version of Node.js

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Run Tests
      run: npm run test
